### ISSUE TITLE
Reading Mode

### ISSUE THREAD

**Issue by dcbo** [noxone/fefe-reader#13]
Is there a way to read Posts without going back to the List?
I would Like to have the Option to Go back and force by swiping on a Post (left/right or up/down)

**Comment by noxone** [comment]
Hi, this sounds like a good idea for a feature.
I will try to implement that.

**Comment by noxone** [comment]
So, this is now realized via buttons in the UI, as I currently down know, how to add the gestures. Maybe I will change that in the future.

I will prepare version 1.2 in the AppStore and then it should be available for all.
